/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thogakade.view.dashboard;

import java.awt.Color;

/**
 *
 * @author Nirodha
 */
public class DashboardForm extends javax.swing.JFrame {

    /**
     * Creates new form DashboardForm
     */
    public DashboardForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        NavigationsPanel = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnCustomers = new javax.swing.JButton();
        btnOrders = new javax.swing.JButton();
        btnItems = new javax.swing.JButton();
        CenterPanel = new javax.swing.JPanel();
        lblNavTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NavigationsPanel.setBackground(Color.decode("#C995A2"));
        NavigationsPanel.setPreferredSize(new java.awt.Dimension(260, 600));
        NavigationsPanel.setLayout(new java.awt.GridBagLayout());

        btnDashboard.setBackground(Color.decode("#000225"));
        btnDashboard.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard.setText("Dashboard");
        btnDashboard.setPreferredSize(new java.awt.Dimension(250, 55));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        NavigationsPanel.add(btnDashboard, gridBagConstraints);

        btnCustomers.setBackground(Color.decode("#000225"));
        btnCustomers.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnCustomers.setForeground(new java.awt.Color(255, 255, 255));
        btnCustomers.setText("Customers");
        btnCustomers.setPreferredSize(new java.awt.Dimension(250, 55));
        btnCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomersActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        NavigationsPanel.add(btnCustomers, gridBagConstraints);

        btnOrders.setBackground(Color.decode("#000225"));
        btnOrders.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnOrders.setForeground(new java.awt.Color(255, 255, 255));
        btnOrders.setText("Orders");
        btnOrders.setPreferredSize(new java.awt.Dimension(250, 55));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        NavigationsPanel.add(btnOrders, gridBagConstraints);

        btnItems.setBackground(Color.decode("#000225"));
        btnItems.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnItems.setForeground(new java.awt.Color(255, 255, 255));
        btnItems.setText("Items");
        btnItems.setPreferredSize(new java.awt.Dimension(250, 55));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        NavigationsPanel.add(btnItems, gridBagConstraints);

        getContentPane().add(NavigationsPanel, java.awt.BorderLayout.WEST);

        CenterPanel.setPreferredSize(new java.awt.Dimension(600, 600));
        CenterPanel.setLayout(new java.awt.BorderLayout());

        lblNavTitle.setBackground(Color.decode("#1E233C"));
        lblNavTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        lblNavTitle.setOpaque(true);
        lblNavTitle.setPreferredSize(new java.awt.Dimension(37, 100));
        CenterPanel.add(lblNavTitle, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(CenterPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCustomersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DashboardForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CenterPanel;
    private javax.swing.JPanel NavigationsPanel;
    private javax.swing.JButton btnCustomers;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnItems;
    private javax.swing.JButton btnOrders;
    private javax.swing.JLabel lblNavTitle;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the CenterPanel
     */
    public javax.swing.JPanel getCenterPanel() {
        return CenterPanel;
    }
}
