/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cierra.lk.view.dashboard;

import cierra.lk.view.dashboard.panel.OrderPanel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import cierra.lk.view.dashboard.panel.CustomerPanel;
import cierra.lk.view.dashboard.panel.ItemPanel;

/**
 *
 * @author Nirodha
 */
public class DashboardForm extends javax.swing.JFrame {

    /**
     * Creates new form DashboardForm
     */
    public DashboardForm() {
        initComponents();
        btnDashboard.doClick();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        NavigationPanel = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        btnOrder = new javax.swing.JButton();
        btnItem = new javax.swing.JButton();
        CenterPanel = new javax.swing.JPanel();
        lblNavTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NavigationPanel.setBackground(Color.decode("#C995A2"));
        NavigationPanel.setPreferredSize(new java.awt.Dimension(260, 600));
        NavigationPanel.setLayout(new java.awt.GridBagLayout());

        btnDashboard.setBackground(Color.decode("#28487B"));
        btnDashboard.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard.setText("Dashboard");
        btnDashboard.setPreferredSize(new java.awt.Dimension(250, 55));
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        NavigationPanel.add(btnDashboard, gridBagConstraints);

        btnCustomer.setBackground(Color.decode("#28487B"));
        btnCustomer.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnCustomer.setText("Customer");
        btnCustomer.setPreferredSize(new java.awt.Dimension(250, 55));
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        NavigationPanel.add(btnCustomer, gridBagConstraints);

        btnOrder.setBackground(Color.decode("#28487B"));
        btnOrder.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnOrder.setText("Order");
        btnOrder.setPreferredSize(new java.awt.Dimension(250, 55));
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        NavigationPanel.add(btnOrder, gridBagConstraints);

        btnItem.setBackground(Color.decode("#28487B"));
        btnItem.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnItem.setForeground(new java.awt.Color(255, 255, 255));
        btnItem.setText("Item");
        btnItem.setPreferredSize(new java.awt.Dimension(250, 55));
        btnItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        NavigationPanel.add(btnItem, gridBagConstraints);

        getContentPane().add(NavigationPanel, java.awt.BorderLayout.WEST);

        CenterPanel.setPreferredSize(new java.awt.Dimension(600, 600));
        CenterPanel.setLayout(new java.awt.BorderLayout());

        lblNavTitle.setBackground(Color.decode("#1E233C"));
        lblNavTitle.setFont(new java.awt.Font("sansserif", 1, 30)); // NOI18N
        lblNavTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblNavTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 20, 8, 8));
        lblNavTitle.setOpaque(true);
        lblNavTitle.setPreferredSize(new java.awt.Dimension(37, 100));
        CenterPanel.add(lblNavTitle, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(CenterPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        removeCenterPanelCenterComponent();
        lblNavTitle.setText("Manage Customer");
        CenterPanel.add(new CustomerPanel(), BorderLayout.CENTER);
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        removeCenterPanelCenterComponent();
        lblNavTitle.setText("Dashboard");
    }//GEN-LAST:event_btnDashboardActionPerformed

    
    private void btnItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemActionPerformed
        removeCenterPanelCenterComponent();
        lblNavTitle.setText("Manage Item");
        CenterPanel.add(new ItemPanel(), BorderLayout.CENTER);
    }//GEN-LAST:event_btnItemActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        removeCenterPanelCenterComponent();
        lblNavTitle.setText("Manage Order");
        CenterPanel.add(new OrderPanel(), BorderLayout.CENTER);
    }//GEN-LAST:event_btnOrderActionPerformed

    private void removeCenterPanelCenterComponent(){
        Component centerComponent = ((BorderLayout) CenterPanel.getLayout())
                .getLayoutComponent(BorderLayout.CENTER);
        if(centerComponent != null){
            CenterPanel.remove(centerComponent);
            CenterPanel.revalidate();
            CenterPanel.repaint();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DashboardForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CenterPanel;
    private javax.swing.JPanel NavigationPanel;
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnItem;
    private javax.swing.JButton btnOrder;
    private javax.swing.JLabel lblNavTitle;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the CenterPanel
     */
    public javax.swing.JPanel getCenterPanel() {
        return CenterPanel;
    }
}
