/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thogakade.view.order;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import thogakade.controller.CustomerController;
import thogakade.controller.ItemController;
import thogakade.controller.OrderController;
import thogakade.model.Customer;
import thogakade.model.Item;
import thogakade.view.customer.AddCustomerForm;

/**
 *
 * @author Nirodha
 */
public class OrderForm extends javax.swing.JFrame {

    /**
     * Creates new form OrderForm
     */
    public OrderForm() {
        initComponents();
        setLocationRelativeTo(null);

        //Load Order Date
        loadDate();

        //Load Order Id
        setOrderId();

        //Load All Customer Ids
        loadAllCustomerIds();

        //Load All Item Codes
        loadAllItemCodes();

        //customize the jTableCart
        customizeTableCart();

        cmbCustomerId.setSelectedItem(null);
        cmbItemCode.setSelectedItem(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPlaceOrderForm = new javax.swing.JLabel();
        labelCustomerId = new javax.swing.JLabel();
        cmbCustomerId = new javax.swing.JComboBox<>();
        btnAddNewCustomer = new javax.swing.JButton();
        labelOrderDate = new javax.swing.JLabel();
        txtOrderDate = new javax.swing.JTextField();
        labelCustomerName = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        labelOrderId = new javax.swing.JLabel();
        lblOrderId = new javax.swing.JLabel();
        labelCode = new javax.swing.JLabel();
        cmbItemCode = new javax.swing.JComboBox<>();
        labelDescription = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        labelUnitPrice = new javax.swing.JLabel();
        lblUnitPrice = new javax.swing.JLabel();
        labelQtyOnHand = new javax.swing.JLabel();
        lblQtyOnHand = new javax.swing.JLabel();
        labelQty = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jScrollPaneCart = new javax.swing.JScrollPane();
        jTableCart = new javax.swing.JTable();
        labelTotal = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnCommit = new javax.swing.JButton();
        btnPlaceOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPlaceOrderForm.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        lblPlaceOrderForm.setForeground(new java.awt.Color(0, 0, 0));
        lblPlaceOrderForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaceOrderForm.setText("Place Order Form");
        lblPlaceOrderForm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelCustomerId.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        labelCustomerId.setForeground(new java.awt.Color(0, 0, 0));
        labelCustomerId.setText("Customer ID : ");

        cmbCustomerId.setBackground(new java.awt.Color(255, 255, 255));
        cmbCustomerId.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        cmbCustomerId.setForeground(new java.awt.Color(0, 0, 0));
        cmbCustomerId.setMaximumRowCount(10);
        cmbCustomerId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCustomerIdItemStateChanged(evt);
            }
        });

        btnAddNewCustomer.setBackground(new java.awt.Color(67, 3, 131));
        btnAddNewCustomer.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        btnAddNewCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnAddNewCustomer.setText("New");
        btnAddNewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewCustomerActionPerformed(evt);
            }
        });

        labelOrderDate.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        labelOrderDate.setForeground(new java.awt.Color(0, 0, 0));
        labelOrderDate.setText("Order Date : ");

        txtOrderDate.setBackground(Color.decode("#787276"));
        txtOrderDate.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        txtOrderDate.setForeground(new java.awt.Color(255, 255, 255));
        txtOrderDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOrderDate.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));

        labelCustomerName.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        labelCustomerName.setForeground(new java.awt.Color(0, 0, 0));
        labelCustomerName.setText("Customer Name :");

        lblCustomerName.setBackground(new java.awt.Color(255, 255, 255));
        lblCustomerName.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        lblCustomerName.setForeground(Color.decode("#24476C"));

        labelOrderId.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        labelOrderId.setForeground(new java.awt.Color(0, 0, 0));
        labelOrderId.setText("Order ID : ");

        lblOrderId.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        lblOrderId.setForeground(Color.decode("#de2e03"));

        labelCode.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        labelCode.setForeground(new java.awt.Color(0, 0, 0));
        labelCode.setText("Code :");

        cmbItemCode.setBackground(new java.awt.Color(255, 255, 255));
        cmbItemCode.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        cmbItemCode.setForeground(new java.awt.Color(0, 0, 0));
        cmbItemCode.setMaximumRowCount(10);
        cmbItemCode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbItemCodeItemStateChanged(evt);
            }
        });

        labelDescription.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        labelDescription.setForeground(new java.awt.Color(0, 0, 0));
        labelDescription.setText("Description : ");

        lblDescription.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        lblDescription.setForeground(Color.decode("#24476C"));

        labelUnitPrice.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        labelUnitPrice.setForeground(new java.awt.Color(0, 0, 0));
        labelUnitPrice.setText("Unit Price :");

        lblUnitPrice.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        lblUnitPrice.setForeground(Color.decode("#24476C"));

        labelQtyOnHand.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        labelQtyOnHand.setForeground(new java.awt.Color(0, 0, 0));
        labelQtyOnHand.setText("Qty. on Hand : ");

        lblQtyOnHand.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        lblQtyOnHand.setForeground(Color.decode("#24476C"));

        labelQty.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        labelQty.setForeground(new java.awt.Color(0, 0, 0));
        labelQty.setText("Qty :");

        txtQty.setBackground(Color.decode("#787276"));
        txtQty.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        txtQty.setForeground(new java.awt.Color(255, 255, 255));
        txtQty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQty.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));

        btnAdd.setBackground(new java.awt.Color(0, 102, 102));
        btnAdd.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setBackground(new java.awt.Color(118, 61, 5));
        btnRemove.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(255, 255, 255));
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        jTableCart.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jTableCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Description", "Qty", "Unit Price", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCart.setRowHeight(20);
        jTableCart.getTableHeader().setReorderingAllowed(false);
        jScrollPaneCart.setViewportView(jTableCart);

        labelTotal.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        labelTotal.setForeground(Color.decode("#e60000"));
        labelTotal.setText("Total :");

        lblTotal.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 0, 0));

        btnCommit.setBackground(new java.awt.Color(112, 16, 112));
        btnCommit.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        btnCommit.setForeground(new java.awt.Color(255, 255, 255));
        btnCommit.setText("Commit");
        btnCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommitActionPerformed(evt);
            }
        });

        btnPlaceOrder.setBackground(new java.awt.Color(3, 95, 48));
        btnPlaceOrder.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        btnPlaceOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnPlaceOrder.setText("Place Order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(379, 379, 379)
                .addComponent(lblPlaceOrderForm, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)
                        .addComponent(btnCommit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addComponent(btnPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(btnAddNewCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelOrderDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOrderDate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCode, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelQty, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelQtyOnHand, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQtyOnHand, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(285, 285, 285)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPaneCart))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblPlaceOrderForm, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddNewCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelOrderDate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOrderDate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelCode, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelQtyOnHand, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQtyOnHand, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelQty, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPaneCart, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCommit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCustomerIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCustomerIdItemStateChanged
        try {
            Customer customer = CustomerController.searchCustomer((String) cmbCustomerId.getSelectedItem());
            lblCustomerName.setText(customer!=null ? customer.getName() : "");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Driver Not Found!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_cmbCustomerIdItemStateChanged

    private void btnAddNewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewCustomerActionPerformed
        AddCustomerForm addCustomerForm = new AddCustomerForm();
        addCustomerForm.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        addCustomerForm.setVisible(true);
        addCustomerForm.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnAddNewCustomerActionPerformed

    private void cmbItemCodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbItemCodeItemStateChanged
        try {
            Item item = ItemController.searchItemByCode((String) cmbItemCode.getSelectedItem());
            if(item!=null){
                lblDescription.setText(item.getDescription());
                lblQtyOnHand.setText(String.valueOf(item.getQtyOnHand()));
                lblUnitPrice.setText(String.valueOf(item.getUnitPrice()));
            }else{
                lblDescription.setText("");
                lblQtyOnHand.setText("");
                lblUnitPrice.setText("");
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Driver Not Found!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_cmbItemCodeItemStateChanged

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTableCart.getModel();
        
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void btnCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCommitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddNewCustomer;
    private javax.swing.JButton btnCommit;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox<String> cmbCustomerId;
    private javax.swing.JComboBox<String> cmbItemCode;
    private javax.swing.JScrollPane jScrollPaneCart;
    private javax.swing.JTable jTableCart;
    private javax.swing.JLabel labelCode;
    private javax.swing.JLabel labelCustomerId;
    private javax.swing.JLabel labelCustomerName;
    private javax.swing.JLabel labelDescription;
    private javax.swing.JLabel labelOrderDate;
    private javax.swing.JLabel labelOrderId;
    private javax.swing.JLabel labelQty;
    private javax.swing.JLabel labelQtyOnHand;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelUnitPrice;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblOrderId;
    private javax.swing.JLabel lblPlaceOrderForm;
    private javax.swing.JLabel lblQtyOnHand;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblUnitPrice;
    private javax.swing.JTextField txtOrderDate;
    private javax.swing.JTextField txtQty;
    // End of variables declaration//GEN-END:variables

    private void loadDate() {
        txtOrderDate.setText(new SimpleDateFormat("yyyy-MM-dd").format(new Date()));
    }

    private void setOrderId() {
        try {
            String lastOrderId = OrderController.getLastOrderId();
            if (lastOrderId != null) {
                lblOrderId.setText(
                        String.format("D%03d", Integer.parseInt(lastOrderId.split("[A-Z]")[1]) + 1));
            } else {
                lblOrderId.setText("D001");
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Driver Not Found!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void loadAllCustomerIds() {
        try {
            for (String customerId : CustomerController.getAllCustomerIds()) {
                cmbCustomerId.addItem(customerId);
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Driver Not Found!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void loadAllItemCodes() {
        try {
            for (String itemCode : ItemController.getAllItemCodes()) {
                cmbItemCode.addItem(itemCode);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            ex.printStackTrace();
        }
    }

    private void customizeTableCart() {
        JTableHeader tableHeader = jTableCart.getTableHeader();
        tableHeader.setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(
                    JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                        JLabel label = (JLabel) super.getTableCellRendererComponent(
                                table, value, isSelected, hasFocus, row, column);
                        
                        label.setFont(new Font("Arial", Font.BOLD, 18));
                        label.setForeground(Color.decode("#2B124C"));
                        label.setBackground(Color.decode("#DABBA7"));
                        label.setHorizontalAlignment(JLabel.CENTER);                        
                        return label;
                    }
        });  
        tableHeader.setPreferredSize(new Dimension(tableHeader.getPreferredSize().width, 35));
    }
}
