/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cierra.lk.view.dashboard.panel;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import cierra.lk.view.order.OrderForm;

/**
 *
 * @author Nirodha
 */
public class OrderPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerPanel
     */
    public OrderPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        midPanel = new javax.swing.JPanel();
        btnPlaceOrder = new javax.swing.JButton();
        btnUpdateOrder = new javax.swing.JButton();
        btnSearchOrder = new javax.swing.JButton();
        btnViewOrders = new javax.swing.JButton();
        btnDeleteOrder = new javax.swing.JButton();

        setBackground(Color.decode("#C3C7C6"));
        setBorder(null);
        setPreferredSize(new java.awt.Dimension(580, 500));
        setLayout(new java.awt.GridBagLayout());

        midPanel.setBackground(Color.decode("#BB9E5F"));
        midPanel.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(Color.decode("#F4DDB8"), 4), BorderFactory.createEmptyBorder(30, 70, 30, 70)));
        midPanel.setPreferredSize(new java.awt.Dimension(480, 480));
        midPanel.setLayout(new java.awt.GridLayout(5, 1, 0, 25));

        btnPlaceOrder.setBackground(Color.decode("#2C263F"));
        btnPlaceOrder.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnPlaceOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnPlaceOrder.setText("Place Order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });
        midPanel.add(btnPlaceOrder);

        btnUpdateOrder.setBackground(Color.decode("#2C263F"));
        btnUpdateOrder.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnUpdateOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateOrder.setText("Update Order Details");
        btnUpdateOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateOrderActionPerformed(evt);
            }
        });
        midPanel.add(btnUpdateOrder);

        btnSearchOrder.setBackground(Color.decode("#2C263F"));
        btnSearchOrder.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnSearchOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchOrder.setText("Search Order");
        btnSearchOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchOrderActionPerformed(evt);
            }
        });
        midPanel.add(btnSearchOrder);

        btnViewOrders.setBackground(Color.decode("#2C263F"));
        btnViewOrders.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnViewOrders.setForeground(new java.awt.Color(255, 255, 255));
        btnViewOrders.setText("View Orders");
        btnViewOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOrdersActionPerformed(evt);
            }
        });
        midPanel.add(btnViewOrders);

        btnDeleteOrder.setBackground(Color.decode("#2C263F"));
        btnDeleteOrder.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDeleteOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteOrder.setText("Delete Order");
        btnDeleteOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteOrderActionPerformed(evt);
            }
        });
        midPanel.add(btnDeleteOrder);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(midPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        new OrderForm().setVisible(true);
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void btnUpdateOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateOrderActionPerformed
        JOptionPane.showMessageDialog(this, "Not Implemented");
    }//GEN-LAST:event_btnUpdateOrderActionPerformed

    private void btnSearchOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchOrderActionPerformed
        JOptionPane.showMessageDialog(this, "Not Implemented");
    }//GEN-LAST:event_btnSearchOrderActionPerformed

    private void btnViewOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrdersActionPerformed
        JOptionPane.showMessageDialog(this, "Not Implemented");
    }//GEN-LAST:event_btnViewOrdersActionPerformed

    private void btnDeleteOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteOrderActionPerformed
        JOptionPane.showMessageDialog(this, "Not Implemented");
    }//GEN-LAST:event_btnDeleteOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteOrder;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnSearchOrder;
    private javax.swing.JButton btnUpdateOrder;
    private javax.swing.JButton btnViewOrders;
    private javax.swing.JPanel midPanel;
    // End of variables declaration//GEN-END:variables
}
